# Generated by Django 2.1.2 on 2018-10-04 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit_bl', models.CharField(max_length=200)),
                ('createted_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('text_bl', models.CharField(max_length=500)),
            ],
        ),
    ]
