# Generated by Django 2.1.1 on 2018-09-16 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='createted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
