# Generated by Django 2.1.3 on 2018-11-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181107_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='owner',
        ),
    ]
