# Generated by Django 2.1.1 on 2018-10-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_list_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
    ]
