# Generated by Django 2.1.3 on 2018-11-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181106_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='created_by',
        ),
    ]
